/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import codes.Cliente;
import codes.ManipulacaoArquivos;
import codes.Pizza;
import codes.Pizzaria;
import codes.SoNumeros;
import javax.swing.JOptionPane;

/**
 *
 * @author romulo
 */
public class TelaClienteComprar extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAdmCadastrar
     */
    public TelaClienteComprar() {
        initComponents();
        tf_ClienteComp_Qtd.setDocument(new SoNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_ClienteComp_Tipo = new javax.swing.JLabel();
        Label_ClienteComp_Sabor2 = new javax.swing.JLabel();
        Label_ClienteComp_Preço = new javax.swing.JLabel();
        tf_ClienteComp_Tipo = new javax.swing.JTextField();
        btn_ClienteComp_Comprar = new javax.swing.JButton();
        btn_ClienteComp_Limpar = new javax.swing.JButton();
        btn_ClienteComp_Buscar = new javax.swing.JButton();
        Label_ClienteComp_Sabor = new javax.swing.JLabel();
        Label_ClienteComp_Qtd = new javax.swing.JLabel();
        tf_ClienteComp_Sabor2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        tf_ClienteComp_Sabor1 = new javax.swing.JTextField();
        tf_ClienteComp_Qtd = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Comprar Pizzas");

        Label_ClienteComp_Tipo.setText("Tipo:");

        Label_ClienteComp_Sabor2.setText("Sabor:");

        Label_ClienteComp_Preço.setText("Preço:");

        tf_ClienteComp_Tipo.setEditable(false);

        btn_ClienteComp_Comprar.setText("Comprar");
        btn_ClienteComp_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteComp_ComprarActionPerformed(evt);
            }
        });

        btn_ClienteComp_Limpar.setText("Limpar");
        btn_ClienteComp_Limpar.setPreferredSize(new java.awt.Dimension(68, 30));
        btn_ClienteComp_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteComp_LimparActionPerformed(evt);
            }
        });

        btn_ClienteComp_Buscar.setText("Buscar");
        btn_ClienteComp_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteComp_BuscarActionPerformed(evt);
            }
        });

        Label_ClienteComp_Sabor.setText("Sabor:");

        Label_ClienteComp_Qtd.setText("Quantidade:");

        tf_ClienteComp_Sabor2.setEditable(false);

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_ClienteComp_Tipo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_ClienteComp_Comprar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ClienteComp_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Label_ClienteComp_Sabor2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_ClienteComp_Sabor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_ClienteComp_Buscar)
                            .addComponent(tf_ClienteComp_Tipo)
                            .addComponent(tf_ClienteComp_Sabor2)
                            .addComponent(tf_ClienteComp_Sabor1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_ClienteComp_Qtd)
                            .addGap(5, 5, 5)
                            .addComponent(tf_ClienteComp_Qtd))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_ClienteComp_Preço)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ClienteComp_Sabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_ClienteComp_Sabor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ClienteComp_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ClienteComp_Tipo)
                    .addComponent(tf_ClienteComp_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ClienteComp_Sabor2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ClienteComp_Sabor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ClienteComp_Preço)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ClienteComp_Qtd)
                    .addComponent(tf_ClienteComp_Qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ClienteComp_Comprar)
                    .addComponent(btn_ClienteComp_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClienteComp_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteComp_LimparActionPerformed
        tf_ClienteComp_Sabor1.setText("");
        tf_ClienteComp_Tipo.setText("");
        tf_ClienteComp_Sabor2.setText("");
        jFormattedTextField1.setText("");
        tf_ClienteComp_Qtd.setText("");
    }//GEN-LAST:event_btn_ClienteComp_LimparActionPerformed

    private void btn_ClienteComp_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteComp_BuscarActionPerformed
        Pizzaria p = new Pizzaria();
        
        Pizza b = p.buscar(tf_ClienteComp_Sabor1.getText());
        if(b!=null){
            tf_ClienteComp_Tipo.setText(b.getTipo());
            tf_ClienteComp_Sabor2.setText(b.getSabor());
            Integer i = b.getPreço();
            // convertendo o preço(Integer) em string para exibir no jTextField
            String preço = (new Integer(i)).toString();
            jFormattedTextField1.setText(preço);
        }else{
            JOptionPane.showMessageDialog(null, "Sabor não encontrado","Aviso ao usuário", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_ClienteComp_BuscarActionPerformed

    private void btn_ClienteComp_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteComp_ComprarActionPerformed
        Pizzaria p = new Pizzaria();
        Cliente l = new Cliente();
        ManipulacaoArquivos m = new ManipulacaoArquivos();

        Pizza b = p.buscar(tf_ClienteComp_Sabor1.getText());
        if(b!=null){
            Integer qtd = Integer.valueOf(tf_ClienteComp_Qtd.getText());
            for(int i=0;i<=qtd-1;i++){
                p.comprar(b);
            }
            p.gravarPizzasObjeto();

            tf_ClienteComp_Sabor1.setText("");
            tf_ClienteComp_Tipo.setText("");
            tf_ClienteComp_Sabor2.setText("");
            jFormattedTextField1.setText("");
            tf_ClienteComp_Qtd.setText("");
            JOptionPane.showMessageDialog(null, "Obrigado por comprar :D");
        }else
            JOptionPane.showMessageDialog(null, "Sabor encontrado");
    }//GEN-LAST:event_btn_ClienteComp_ComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_ClienteComp_Preço;
    private javax.swing.JLabel Label_ClienteComp_Qtd;
    private javax.swing.JLabel Label_ClienteComp_Sabor;
    private javax.swing.JLabel Label_ClienteComp_Sabor2;
    private javax.swing.JLabel Label_ClienteComp_Tipo;
    private javax.swing.JButton btn_ClienteComp_Buscar;
    private javax.swing.JButton btn_ClienteComp_Comprar;
    private javax.swing.JButton btn_ClienteComp_Limpar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_ClienteComp_Qtd;
    private javax.swing.JTextField tf_ClienteComp_Sabor1;
    private javax.swing.JTextField tf_ClienteComp_Sabor2;
    private javax.swing.JTextField tf_ClienteComp_Tipo;
    // End of variables declaration//GEN-END:variables
}
