/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import codes.Cliente;
import codes.ManipulacaoArquivos;
import static codes.ManipulacaoArquivos.recuperaPizzas;
import codes.Pizza;
import codes.Pizzaria;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author romulo
 */
public class TelaClienteOrdenar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ordenar
     */
    public TelaClienteOrdenar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        btn_ClienteOrd_MaiorPreço = new javax.swing.JButton();
        btn_ClienteOrd_MaisVendidas = new javax.swing.JButton();
        btn_ClienteOrd_Limpar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Listar por Ordem");

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        btn_ClienteOrd_MaiorPreço.setText("Maior preço");
        btn_ClienteOrd_MaiorPreço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteOrd_MaiorPreçoActionPerformed(evt);
            }
        });

        btn_ClienteOrd_MaisVendidas.setText("Mais vendidas");
        btn_ClienteOrd_MaisVendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteOrd_MaisVendidasActionPerformed(evt);
            }
        });

        btn_ClienteOrd_Limpar.setText("Limpar");
        btn_ClienteOrd_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteOrd_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ClienteOrd_MaiorPreço)
                        .addGap(59, 59, 59)
                        .addComponent(btn_ClienteOrd_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btn_ClienteOrd_MaisVendidas)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ClienteOrd_MaiorPreço)
                    .addComponent(btn_ClienteOrd_MaisVendidas)
                    .addComponent(btn_ClienteOrd_Limpar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClienteOrd_MaisVendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteOrd_MaisVendidasActionPerformed
        jTextArea.setText("");
        Pizzaria p = new Pizzaria();
        Cliente l = new Cliente();
        ManipulacaoArquivos m = new ManipulacaoArquivos();

        ArrayList<Pizza> auxiliar = new ArrayList<Pizza>();
        ArrayList<Pizza> pizzas = recuperaPizzas();
        auxiliar = l.ordenarMaisVendidas(pizzas);
        try {
            // salva a list usando um método prórpio pois ele criar um arquivo só para
            // pizzas em ordem de preço
            m.salvarListaTXTOrdenadaPelasVendas(auxiliar);
            String texto = m.lerListaTXTOrdenadoPelasVendas();
            jTextArea.setText(texto);
        } catch (IOException ex) {
            Logger.getLogger(TelaClienteOrdenar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ClienteOrd_MaisVendidasActionPerformed

    private void btn_ClienteOrd_MaiorPreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteOrd_MaiorPreçoActionPerformed
        jTextArea.setText("");
        Pizzaria p = new Pizzaria();
        Cliente l = new Cliente();
        ManipulacaoArquivos m = new ManipulacaoArquivos();
        //próximas 3 linhas estão criando um arquivo de lista de pizzas ja ordenas
        // pra ser usada na tela cliente ordenar
        ArrayList<Pizza> auxiliar = new ArrayList<Pizza>();
        // salva em uma list as pizzas cadastradas
        ArrayList<Pizza> pizzas = recuperaPizzas();
        // salva numa list auxiliar o retorno da lista pizza ordenada
        auxiliar = l.ordenarMaiorPreço(pizzas);
        try {
            // salva a list usando um método prórpio pois ele criar um arquivo só para
            // pizzas em ordem de preço
            m.salvarListaTXTOrdenada(auxiliar);
            String texto = m.lerListaTXTOrdenado();
            jTextArea.setText(texto);
        } catch (IOException ex) {
            Logger.getLogger(TelaClienteOrdenar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /*for(Pizza e: pizzas){
            jTextArea.setText(e.toString());
        }*/
    }//GEN-LAST:event_btn_ClienteOrd_MaiorPreçoActionPerformed

    private void btn_ClienteOrd_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteOrd_LimparActionPerformed
        jTextArea.setText("");
    }//GEN-LAST:event_btn_ClienteOrd_LimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ClienteOrd_Limpar;
    private javax.swing.JButton btn_ClienteOrd_MaiorPreço;
    private javax.swing.JButton btn_ClienteOrd_MaisVendidas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
