/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import codes.ManipulacaoArquivos;
import codes.Pizza;
import codes.Pizzaria;
import javax.swing.JOptionPane;

/**
 *
 * @author romulo
 */
public class TelaAdmRemover extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAdmRemover
     */
    public TelaAdmRemover() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_AdmRem_Sabor = new javax.swing.JLabel();
        btn_AdmRem_Remover = new javax.swing.JButton();
        jTextField = new javax.swing.JTextField();
        btn_AdmRem_Buscar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Remover Pizzas");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(300, 135));

        Label_AdmRem_Sabor.setText("Sabor:");

        btn_AdmRem_Remover.setText("Remover");
        btn_AdmRem_Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdmRem_RemoverActionPerformed(evt);
            }
        });

        btn_AdmRem_Buscar.setText("Buscar");
        btn_AdmRem_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdmRem_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_AdmRem_Sabor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_AdmRem_Buscar)
                        .addGap(29, 29, 29)
                        .addComponent(btn_AdmRem_Remover)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AdmRem_Sabor)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AdmRem_Buscar)
                    .addComponent(btn_AdmRem_Remover))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AdmRem_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdmRem_BuscarActionPerformed
        Pizzaria p = new Pizzaria();
        Pizza b = p.buscar(jTextField.getText());
        if(b==null){
            JOptionPane.showMessageDialog(null, "Sabor não encontrado","Aviso ao usuário", JOptionPane.WARNING_MESSAGE);
        }else
            JOptionPane.showMessageDialog(null, "Sabor encontrado");
    }//GEN-LAST:event_btn_AdmRem_BuscarActionPerformed

    private void btn_AdmRem_RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdmRem_RemoverActionPerformed
        Pizzaria p = new Pizzaria();
        ManipulacaoArquivos i = new ManipulacaoArquivos();
        Pizza b = p.buscar(jTextField.getText());
        String sabor = b.getSabor();
        p.remover(sabor);
        p.gravarPizzasObjeto();
        JOptionPane.showMessageDialog(null, "Sabor: "+jTextField.getText()+" foi removido");
        jTextField.setText("");
    }//GEN-LAST:event_btn_AdmRem_RemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_AdmRem_Sabor;
    private javax.swing.JButton btn_AdmRem_Buscar;
    private javax.swing.JButton btn_AdmRem_Remover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
