/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
/**
 *
 * @author romulo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/pizza3.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 13, 599, 400, this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAdm = new javax.swing.JMenu();
        menuAdmCadastrar = new javax.swing.JMenuItem();
        menuAdmAlterar = new javax.swing.JMenuItem();
        menuAdmRemover = new javax.swing.JMenuItem();
        menuAdmListar = new javax.swing.JMenuItem();
        MenuCliente = new javax.swing.JMenu();
        menuClienteComprar = new javax.swing.JMenuItem();
        menuClienteOrdenar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaria da Engenharia");
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        jMenuBar1.setBackground(java.awt.Color.darkGray);
        jMenuBar1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        MenuAdm.setText("Administrador");

        menuAdmCadastrar.setText("Cadastrar");
        menuAdmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdmCadastrarActionPerformed(evt);
            }
        });
        MenuAdm.add(menuAdmCadastrar);

        menuAdmAlterar.setText("Alterar");
        menuAdmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdmAlterarActionPerformed(evt);
            }
        });
        MenuAdm.add(menuAdmAlterar);

        menuAdmRemover.setText("Remover");
        menuAdmRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdmRemoverActionPerformed(evt);
            }
        });
        MenuAdm.add(menuAdmRemover);

        menuAdmListar.setText("Listar");
        menuAdmListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdmListarActionPerformed(evt);
            }
        });
        MenuAdm.add(menuAdmListar);

        jMenuBar1.add(MenuAdm);

        MenuCliente.setText("Cliente");

        menuClienteComprar.setText("Comprar");
        menuClienteComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteComprarActionPerformed(evt);
            }
        });
        MenuCliente.add(menuClienteComprar);

        menuClienteOrdenar.setText("Ordenar");
        menuClienteOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteOrdenarActionPerformed(evt);
            }
        });
        MenuCliente.add(menuClienteOrdenar);

        jMenuBar1.add(MenuCliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAdmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdmAlterarActionPerformed
        TelaAdmAlterar telaAltPizza = new TelaAdmAlterar();
        jDesktopPane1.add(telaAltPizza);
        telaAltPizza.setVisible(true);
    }//GEN-LAST:event_menuAdmAlterarActionPerformed

    private void menuAdmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdmCadastrarActionPerformed
        TelaAdmCadastrar telaCadPizza = new TelaAdmCadastrar();
        jDesktopPane1.add(telaCadPizza);
        telaCadPizza.setVisible(true);
    }//GEN-LAST:event_menuAdmCadastrarActionPerformed

    private void menuAdmRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdmRemoverActionPerformed
        TelaAdmRemover telaRemPizza = new TelaAdmRemover();
        jDesktopPane1.add(telaRemPizza);
        telaRemPizza.setVisible(true);
    }//GEN-LAST:event_menuAdmRemoverActionPerformed

    private void menuAdmListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdmListarActionPerformed
        TelaAdmListar telaListPizza = new TelaAdmListar();
        jDesktopPane1.add(telaListPizza);
        telaListPizza.setVisible(true);
    }//GEN-LAST:event_menuAdmListarActionPerformed

    private void menuClienteComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteComprarActionPerformed
        TelaClienteComprar telaCompPizza = new TelaClienteComprar();
        jDesktopPane1.add(telaCompPizza);
        telaCompPizza.setVisible(true);
    }//GEN-LAST:event_menuClienteComprarActionPerformed

    private void menuClienteOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteOrdenarActionPerformed
        TelaClienteOrdenar telaOrdPizza = new TelaClienteOrdenar();
        jDesktopPane1.add(telaOrdPizza);
        telaOrdPizza.setVisible(true);
    }//GEN-LAST:event_menuClienteOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdm;
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAdmAlterar;
    private javax.swing.JMenuItem menuAdmCadastrar;
    private javax.swing.JMenuItem menuAdmListar;
    private javax.swing.JMenuItem menuAdmRemover;
    private javax.swing.JMenuItem menuClienteComprar;
    private javax.swing.JMenuItem menuClienteOrdenar;
    // End of variables declaration//GEN-END:variables
}
