/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import codes.ManipulacaoArquivos;
import codes.Pizza;
import codes.Pizzaria;
import codes.SoNumeros;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author romulo
 */
public class TelaAdmCadastrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAdmCadastrar
     */
    public TelaAdmCadastrar() {
        initComponents();
        tf_AdmCad_Preço.setDocument(new SoNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_AdmCad_Tipo = new javax.swing.JLabel();
        cb_AdmCad_Salgada = new javax.swing.JCheckBox();
        cb_AdmCad_Doce = new javax.swing.JCheckBox();
        Label_AdmCad_Sabor = new javax.swing.JLabel();
        Label_AdmCad_Preço = new javax.swing.JLabel();
        tf_AdmCad_Preço = new javax.swing.JTextField();
        tf_AdmCad_Sabor = new javax.swing.JTextField();
        btn_AdmCad_Finalizar = new javax.swing.JButton();
        btn_AdmCad_Limpar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Pizza");

        Label_AdmCad_Tipo.setText("Tipo:");

        cb_AdmCad_Salgada.setText("Salgada");
        cb_AdmCad_Salgada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_AdmCad_SalgadaActionPerformed(evt);
            }
        });

        cb_AdmCad_Doce.setText("Doce");
        cb_AdmCad_Doce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_AdmCad_DoceActionPerformed(evt);
            }
        });

        Label_AdmCad_Sabor.setText("Sabor:");

        Label_AdmCad_Preço.setText("Preço:");

        tf_AdmCad_Preço.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btn_AdmCad_Finalizar.setText("Finalizar");
        btn_AdmCad_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdmCad_FinalizarActionPerformed(evt);
            }
        });

        btn_AdmCad_Limpar.setText("Limpar");
        btn_AdmCad_Limpar.setPreferredSize(new java.awt.Dimension(68, 30));
        btn_AdmCad_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdmCad_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_AdmCad_Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_AdmCad_Sabor))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_AdmCad_Tipo)
                            .addGap(42, 42, 42)
                            .addComponent(cb_AdmCad_Salgada)
                            .addGap(18, 18, 18)
                            .addComponent(cb_AdmCad_Doce)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_AdmCad_Finalizar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_AdmCad_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_AdmCad_Preço)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_AdmCad_Preço, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AdmCad_Tipo)
                    .addComponent(cb_AdmCad_Salgada)
                    .addComponent(cb_AdmCad_Doce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_AdmCad_Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_AdmCad_Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_AdmCad_Preço)
                    .addComponent(tf_AdmCad_Preço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_AdmCad_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AdmCad_Finalizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AdmCad_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdmCad_LimparActionPerformed
        tf_AdmCad_Preço.setText("");
        tf_AdmCad_Sabor.setText("");
        
    }//GEN-LAST:event_btn_AdmCad_LimparActionPerformed

    private void cb_AdmCad_SalgadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_AdmCad_SalgadaActionPerformed
        cb_AdmCad_Doce.setSelected(false);
    }//GEN-LAST:event_cb_AdmCad_SalgadaActionPerformed

    private void cb_AdmCad_DoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_AdmCad_DoceActionPerformed
        cb_AdmCad_Salgada.setSelected(false);
    }//GEN-LAST:event_cb_AdmCad_DoceActionPerformed

    private void btn_AdmCad_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdmCad_FinalizarActionPerformed
        Pizzaria p = new Pizzaria();
        String l = null;
        ManipulacaoArquivos i = new ManipulacaoArquivos();
        // verificando qual checkBox está selecionada e salvando seu "valor"
        if(cb_AdmCad_Salgada.isSelected()){
            l = "Salgada";
        }else if(cb_AdmCad_Doce.isSelected()){
            l = "Doce";
        }else
            JOptionPane.showMessageDialog(null, "Selecione o sabor.","Aviso ao usuário", JOptionPane.WARNING_MESSAGE);
        // convertendo o texto na jTextFiel preço em inteiro
        Integer preço = Integer.valueOf(tf_AdmCad_Preço.getText());
        p.CadastrarPizza(l, tf_AdmCad_Sabor.getText(), preço);
        

        
        //JOptionPane.showMessageDialog(null, p.salvarListaTXT());
        p.gravarPizzasObjeto();
        
        
        
        tf_AdmCad_Preço.setText("");
        tf_AdmCad_Sabor.setText("");
        
    }//GEN-LAST:event_btn_AdmCad_FinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_AdmCad_Preço;
    private javax.swing.JLabel Label_AdmCad_Sabor;
    private javax.swing.JLabel Label_AdmCad_Tipo;
    private javax.swing.JButton btn_AdmCad_Finalizar;
    private javax.swing.JButton btn_AdmCad_Limpar;
    private javax.swing.JCheckBox cb_AdmCad_Doce;
    private javax.swing.JCheckBox cb_AdmCad_Salgada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_AdmCad_Preço;
    private javax.swing.JTextField tf_AdmCad_Sabor;
    // End of variables declaration//GEN-END:variables
}
